import type { Metadata } from "next";
import { DM_Sans } from 'next/font/google'
import { Space_Mono } from 'next/font/google'
import { cn } from '@/lib/utils'
import './globals.css'


import Header from "@/components/Header";

//web3 Reown
import ContextProvider from '@/context'
import { headers } from 'next/headers'

const fontHeading = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
})

const fontBody = Space_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-body',
  weight: "400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookies = (await headers()).get('cookie')
  return (
    <html lang="en" className={cn(fontHeading.variable, fontBody.variable)}>
      <ContextProvider cookies={cookies}>
      <body className="antialiased font-body bg-background text-foreground">
        <div className="flex flex-col min-h-screen">
          <Header />
          {children}
        </div>
      </body>
      </ContextProvider>
    </html>
  );
}